### ISSUE TITLE
Put built css as style field

### ISSUE THREAD

**Issue by PatrikLythell** [jxnblk/gravitons#1]
Put in the built css as the package.json "style" field instead of the source file.

Helps if you're using @import tools in your build step for importing css without the need for the build tool to know how to/if to build gravitons.

**Comment by jxnblk** [comment]
I think I'd rather keep the pre-compiled CSS in the style field, since that's something tools like Post CSS use and it allows the user to adjust the default values. If someone wants to import the compiled version, they can use `@import "gravitons/css/gravitons.css"`
